### PR TITLE
added other colors and screenshots for later use

### PR DESCRIPTION
**Pull request by treymerkley**
Everything should be here, but double-check on the off chance a color is missing or the screenshots look too personal.

### CODE REVIEW

**Comment by Ferdi265** [comment]
Looks nice!

One thing though: Every .colors file has a `@THEME@` directive at the top. That's currently "SolarizedDarkGreen" in all your new color files, should be the name of the theme (i.e. SolarizedDarkCyan)

After that, your PR looks ready for merge :+1:

I plan on reworking the .colors machinery to remove this duplicate theme name thing, and maybe make it a little smarter than pure search / replace.

**Comment by treymerkley** [comment]
Alright, fixed. Sounds good to me. Really, since so much is shared, a couple of templates could be made and the colors acting as modules. 

Actually, is the .colors thing more reliant on Python or Inkscape? I think you've mentioned that using Inkscape takes a little extra time, so I was wondering if there was a graphical python package that could be incorporated into the repo.

**Comment by Ferdi265** [comment]
The colors thing is just search/replace color strings in the .scss files, .svg files and .gtkrc files.We need inkscape, because the GTK uses pngs for the icons, and we have to generate them from the SVG. Doing it _in_ python wouldn't make it faster since we still need to do as much work.The plan is like you said, better and templated color files (maybe in YAML or JSON format, or something new / special), but in the end we can't really skip the inkscape part

**Comment by treymerkley** [comment]
Good to know! I closed my issue, too.

**Pull request merged**
